# SITE SETUP.
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance.
appearance:
  mode: system
  color: blue

# SEO.
marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "Personal blog and portfolio of Arvin Zhao (赵吉忱)."
    twitter: "arvinzjc"
  verification:
    google: "" # Verified via Cloudflare.
    bing: "" # Imported from GSC.
    baidu: "" # Filing my domain in PRC is currently impossible.
    yandex: "" # Verified via a DNS record.
    pinterest: "" # Verified via a DNS record.

# Site header.
header:
  navbar:
    enable: true
    fixed_to_top: true
    logo:
      text: "Arvin Zhao"
      filename: "logo.png"
    show_theme_chooser: true
    show_search: true
    highlight_active_link: true

# Site footer.
footer:
  copyright:
    notice: "© {year} ArvinZJC"

# Localisation.
locale:
  date_format: "2 Jan, 2006"
  time_format: "15:04"

# Site features
features:
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: "giscus"
    giscus:
      repo: "ArvinZJC/isarvin.com"
      repo_id: "R_kgDONxLEGA"
      category: "Announcements"
      category_id: "DIC_kwDONxLEGM4CmiRG"
      theme: preferred_color_scheme
      language_code: en
      mapping: pathname
  math:
    enable: true
  privacy_pack:
    enable: false
